### ISSUE TITLE
파이썬 한국어 강좌 제안

### ISSUE THREAD

**Issue by AkiaCode** [Lapis0875/PythonTutorial#16]
파이썬 한국어 강좌를 더욱 보기 쉅게 github page로  해보시는 건 어떤가요?

**Comment by Lapis0875** [comment]
github page...라
확실히 저장소에서 README.md를 읽는것보단 그 편이 더 좋아보이네요.
현재 Goorm EDU에 강좌 내용을 옮기는 작업을 진행하고 있으니, github pages 쪽은 기여를 받아 진행해보면 어떨까 싶네요 😀 
고려해보겠습니다!

**Comment by AkiaCode** [comment]
알겠습니다 @Lapis0875

**Comment by AkiaCode** [comment]
* 참고 자료: https://nicolas-van.github.io/easy-markdown-to-github-pages/

**Comment by AkiaCode** [comment]
@Lapis0875  브런치를 새롭게 파는 건 어떤가요? 
이름은 `github-page`가 좋을 거 같습니다

**Comment by Lapis0875** [comment]
하게되면 기존 브랜치와 경로 설정을 달리해야 할 테니, 깃허브 페이지용 브랜치를 새로 파게될 것 같아요 😀

**Comment by AkiaCode** [comment]
하긴 그럴 거 같긴 하네요

**Comment by sunrabbit123** [comment]
vuepress를 이용하여 github pages를 하는 방안은 어떨까요?
처음부터 만들기보다는 기존에 있는 것을 확장해나가면서 만드는 방향도 괜찮을 것 이라 생각해요

**Comment by Lapis0875** [comment]
#20 에서 PR을 받았습니다! 노고에 감사드립니다 👍
